import type { Metadata } from "next";

import "./globals.css";
import "98.css";

// 导入字体样式
import localFont from "next/font/local";

// 加载本地字体
const msFont = localFont({
	src: "../public/fonts/MSW98UI-Regular.woff",
	variable: "--ms-font",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={msFont.variable}>
			<body style={{ overflow: "hidden", fontFamily: "var(--ms-font)" }}>
				{children}
			</body>
		</html>
	);
}
